### ISSUE TITLE
Syntax and Type errors in production

### ISSUE THREAD

**Issue by npezza93** [alchaplinsky/polymer-rails#51]
In development everything works as it is supposed to with a bunch of polymer elements in conjunction with  the polymer-elements-rails gem. When I launch to Heroku, however, no Polymer elements are rendered and I get a full suite of errors as seen in the attached. Did I miss doing something special in production? 
![capture](https://cloud.githubusercontent.com/assets/5059927/8295148/d864767e-190f-11e5-9d5a-ee25f713c835.PNG)

**Comment by alchapone** [comment]
@npezza93 Please, provide a list of elements you're including to your `application.html` manifest

**Comment by npezza93** [comment]
![capture](https://cloud.githubusercontent.com/assets/5059927/8308162/4940b296-1991-11e5-91c4-6ecc9aecba42.PNG)

**Comment by nonameolsson** [comment]
Could this also have anything to do with https://github.com/PolymerElements/paper-drawer-panel/issues/74?

**Comment by npezza93** [comment]
If I remove paper-drawer-panel, none of the elements still render correctly and these are the errors I get. 
![capture](https://cloud.githubusercontent.com/assets/5059927/8331101/5cab514c-1a54-11e5-83e7-9b6d9dab314e.PNG)

**Comment by nonameolsson** [comment]
Strange though. I haven't actually tried it in production yet =/
